# Generated by Django 4.1.5 on 2023-02-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_rename_invitedas_attencence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attencence',
            new_name='Attendence',
        ),
    ]
