# Generated by Django 4.1.5 on 2023-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_attendence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'verbose_name_plural': 'Attendant'},
        ),
        migrations.AlterField(
            model_name='attendence',
            name='name_attendence',
            field=models.CharField(max_length=255, null=True, verbose_name='Attendant'),
        ),
    ]
