# Generated by Django 4.1.5 on 2023-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_institution_delete_invitedinstitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name_institution',
            field=models.CharField(max_length=255, null=True, verbose_name='Institution'),
        ),
    ]
