# Generated by Django 4.1.5 on 2023-02-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_institution_name_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='unitADN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_unit', models.CharField(max_length=255, null=True, verbose_name='Unit Of:')),
                ('abreviation', models.CharField(max_length=10, null=True, verbose_name='Abreviation:')),
            ],
            options={
                'verbose_name_plural': 'name_unit',
            },
        ),
        migrations.CreateModel(
            name='DepartmentADN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=255, null=True, verbose_name='Unit Of:')),
                ('unitadn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unitadn', to='institute.unitadn', verbose_name='Unit Of:')),
            ],
            options={
                'verbose_name_plural': 'Name Department',
            },
        ),
    ]
