# Generated by Django 4.1.5 on 2023-03-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_unitadn_departmentadn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentadn',
            options={'verbose_name_plural': 'Department ADN'},
        ),
        migrations.AlterModelOptions(
            name='unitadn',
            options={'verbose_name_plural': 'Unit ADN'},
        ),
    ]
