# Generated by Django 4.1.5 on 2023-02-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_agenda_location_alter_commentinformative_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedInstitue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institution', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='description',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='invitedinstitue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.invitedinstitue'),
            preserve_default=False,
        ),
    ]
