# Generated by Django 4.1.5 on 2023-02-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_agenda_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('-start_time',), 'verbose_name_plural': 'Agenda'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='invitedinstitue',
        ),
    ]
