# Generated by Django 4.1.5 on 2023-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_agenda_options_remove_agenda_invitedinstitue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedinstitute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
