# Generated by Django 4.1.5 on 2023-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_agenda_invitedinstitue_alter_invitedinstitute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedinstitute',
            name='name_institution',
            field=models.CharField(max_length=255, null=True, verbose_name='Institute Invited'),
        ),
    ]
