# Generated by Django 4.1.5 on 2023-02-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_invitedinstitute_name_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitedinstitute',
            options={'verbose_name_plural': 'Institute Invited'},
        ),
    ]
