# Generated by Django 4.1.5 on 2023-02-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_invitedinstitute_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='invitedinstitue',
        ),
        migrations.DeleteModel(
            name='InvitedInstitute',
        ),
    ]
