# Generated by Django 4.1.5 on 2023-02-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_name_institution_invitedinstitute_name_institute'),
        ('event', '0012_remove_agenda_invitedinstitue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='invitedinstitue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='institute.invitedinstitute'),
            preserve_default=False,
        ),
    ]
