# Generated by Django 4.1.5 on 2023-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_rename_active_commentinformative_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinformative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
