# Generated by Django 4.1.5 on 2023-02-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_commentinformative_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informative',
            name='description',
        ),
    ]
