# Generated by Django 4.1.5 on 2023-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_agenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='observation',
            field=models.TextField(null=True),
        ),
    ]
