# Generated by Django 4.1.5 on 2023-02-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_attendence_options_and_more'),
        ('event', '0019_agenda_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='attendence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='institute.attendence', verbose_name='Attendant'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='invitedinstitue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='institute.invitedinstitute', verbose_name='Institute'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='yearagenda',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023)], default=2023, verbose_name='year'),
        ),
        migrations.CreateModel(
            name='HistAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_postpone', models.DateTimeField()),
                ('end_time_postpone', models.DateTimeField()),
                ('location_new', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histagenda', to='event.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name_plural': 'Agenda',
                'ordering': ('-start_time_postpone',),
            },
        ),
    ]
