# Generated by Django 4.1.5 on 2023-02-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_histagenda_options_remove_histagenda_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='location',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='end_time_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='start_time_new',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nota Informative'),
        ),
    ]
