# Generated by Django 4.1.5 on 2023-02-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_institution_delete_invitedinstitute'),
        ('event', '0023_remove_agenda_invitedinstitue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='institute.institution', verbose_name='Institution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histagenda',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histagenda', to='institute.institution', verbose_name='Institution'),
            preserve_default=False,
        ),
    ]
