# Generated by Django 4.1.5 on 2023-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_agenda_institution_histagenda_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=200, unique=True, verbose_name='Category Agenda')),
            ],
            options={
                'verbose_name_plural': 'Category Agenda',
            },
        ),
    ]
