# Generated by Django 4.1.5 on 2023-02-26 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0027_alter_agenda_observation_alter_agenda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinformative',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentinformative',
            name='problems',
            field=models.TextField(blank=True, verbose_name='Problems:'),
        ),
        migrations.AddField(
            model_name='commentinformative',
            name='results',
            field=models.TextField(blank=True, verbose_name='Results:'),
        ),
        migrations.AddField(
            model_name='commentinformative',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentInformative', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Agenda'),
        ),
    ]
