# Generated by Django 4.1.5 on 2023-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_remove_commentinformative_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinformative',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
