# Generated by Django 4.1.5 on 2023-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_commentinformative_is_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinformative',
            name='is_comment',
        ),
        migrations.AddField(
            model_name='informative',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
