# Generated by Django 4.1.5 on 2023-02-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_remove_commentinformative_is_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentinformative',
            name='is_done',
        ),
    ]
