# Generated by Django 4.1.5 on 2023-02-26 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0032_remove_commentinformative_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Agenda')),
                ('title_slug', models.SlugField(max_length=255, unique=True, verbose_name='Title-Slug')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Aproved', 'Aproved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestagenda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Request Agenda',
            },
        ),
    ]
