# Generated by Django 4.1.5 on 2023-02-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_requestagenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestagenda',
            old_name='updated_at',
            new_name='aproved_at',
        ),
        migrations.RenameField(
            model_name='requestagenda',
            old_name='created_at',
            new_name='requested_at',
        ),
    ]
