# Generated by Django 4.1.5 on 2023-02-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_rename_updated_at_requestagenda_aproved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestagenda',
            name='status',
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestagenda',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Request Agenda:'),
        ),
    ]
