# Generated by Django 4.1.5 on 2023-02-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_remove_requestagenda_status_requestagenda_is_approve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestagenda',
            old_name='aproved_at',
            new_name='approved_at',
        ),
    ]
