# Generated by Django 4.1.5 on 2023-02-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_institution_name_institution'),
        ('event', '0036_rename_aproved_at_requestagenda_approved_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestagenda',
            options={},
        ),
        migrations.RenameField(
            model_name='requestagenda',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requestagenda',
            old_name='is_approve',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='requestagenda',
            old_name='approved_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='attendence',
        ),
        migrations.RemoveField(
            model_name='histagenda',
            name='attendence',
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='catagenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestagenda', to='event.catagenda', verbose_name='Category Agenda:'),
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestagenda', to='institute.institution', verbose_name='Institution:'),
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestagenda',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], max_length=20, null=True),
        ),
    ]
