# Generated by Django 4.1.5 on 2023-02-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_rename_aproved_at_requestagenda_approved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='attendence',
        ),
        migrations.RemoveField(
            model_name='histagenda',
            name='attendence',
        ),
    ]
