# Generated by Django 4.1.5 on 2023-02-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_remove_agenda_attendence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestagenda',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
