# Generated by Django 4.1.5 on 2023-03-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_alter_histagenda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagenda',
            name='name_category_slug',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Category Agenda Slug'),
        ),
    ]
