# Generated by Django 4.1.5 on 2023-02-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_agenda_commentinformative_informative_yearagenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commentinformative',
            name='comment',
            field=models.TextField(verbose_name='Add New Comment'),
        ),
    ]
