# Generated by Django 4.1.5 on 2023-02-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_invitedinstitue_remove_agenda_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedInstitue',
            new_name='InvitedInstitute',
        ),
    ]
