# Generated by Django 4.1.5 on 2023-02-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_invitedinstitue_invitedinstitute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'managed': True, 'ordering': ('-start_time',), 'verbose_name_plural': 'Agenda'},
        ),
    ]
