# Generated by Django 4.1.5 on 2023-02-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_invitedinstitute_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='invitedinstitue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.invitedinstitute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitedinstitute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
