# Generated by Django 4.1.5 on 2023-02-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_rename_attencence_attendence'),
        ('event', '0013_agenda_invitedinstitue'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='attendence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='institute.attendence'),
            preserve_default=False,
        ),
    ]
