# Generated by Django 4.1.5 on 2023-02-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_agenda_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentinformative',
            old_name='active',
            new_name='is_active',
        ),
    ]
