# Generated by Django 4.1.5 on 2023-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_informative_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
