# Generated by Django 4.1.5 on 2023-02-15 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_attendence_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0020_alter_agenda_attendence_alter_agenda_invitedinstitue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histagenda',
            options={'ordering': ('-start_time_new',), 'verbose_name_plural': 'Agenda History '},
        ),
        migrations.RemoveField(
            model_name='histagenda',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='histagenda',
            name='end_time_postpone',
        ),
        migrations.RemoveField(
            model_name='histagenda',
            name='start_time_postpone',
        ),
        migrations.AddField(
            model_name='histagenda',
            name='attendence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='histagenda', to='institute.attendence', verbose_name='Attendant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histagenda',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='end_time_new',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='invitedinstitue',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='histagenda', to='institute.invitedinstitute', verbose_name='Institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histagenda',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='observation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='start_time_new',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='histagenda',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], default=7, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histagenda',
            name='title',
            field=models.CharField(default=2, max_length=200, unique=True, verbose_name='Agenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histagenda',
            name='title_slug',
            field=models.SlugField(default=3, max_length=255, unique=True, verbose_name='Title-Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='histagenda',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='histagenda', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
