# Generated by Django 4.1.5 on 2023-02-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_agenda_location_alter_agenda_observation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='invitedinstitue',
        ),
        migrations.RemoveField(
            model_name='histagenda',
            name='invitedinstitue',
        ),
    ]
