# Generated by Django 4.1.5 on 2023-02-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_catagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='catagenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.catagenda', verbose_name='Category Agenda'),
            preserve_default=False,
        ),
    ]
