# Generated by Django 4.1.5 on 2023-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_agenda_catagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='observation',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], max_length=20),
        ),
    ]
