# Generated by Django 4.1.5 on 2023-02-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_commentinformative_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentinformative',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
    ]
