# Generated by Django 4.1.5 on 2023-02-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_alter_requestagenda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestagenda',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Request Agenda '},
        ),
        migrations.AddField(
            model_name='histagenda',
            name='catagenda',
            field=models.CharField(max_length=25, null=True, verbose_name='Category Agenda'),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='institution',
            field=models.CharField(max_length=255, null=True, verbose_name='Agenda Set'),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Agenda'),
        ),
    ]
