# Generated by Django 4.1.5 on 2023-03-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_requestagenda_options_histagenda_catagenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histagenda',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
