# Generated by Django 4.1.5 on 2023-04-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_catagenda_name_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='observation',
            field=models.TextField(blank=True, verbose_name='OBSERVATION / REASON'),
        ),
    ]
