# Generated by Django 4.2.19 on 2025-02-11 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_alter_attendence_options_alter_institution_options_and_more'),
        ('event', '0041_alter_agenda_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ('-start_time',), 'verbose_name_plural': 'Ajenda'},
        ),
        migrations.AlterModelOptions(
            name='catagenda',
            options={'verbose_name_plural': 'Kategoria Ajenda'},
        ),
        migrations.AlterModelOptions(
            name='histagenda',
            options={'ordering': ('-start_time_new',), 'verbose_name_plural': 'Historia Ajenda '},
        ),
        migrations.AlterModelOptions(
            name='informative',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Informativu'},
        ),
        migrations.AlterModelOptions(
            name='requestagenda',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Pedidu Ajenda '},
        ),
        migrations.AlterModelOptions(
            name='yearagenda',
            options={'ordering': ('-year',), 'verbose_name_plural': 'Ajenda Tuir Tinan'},
        ),
        migrations.AlterField(
            model_name='agenda',
            name='catagenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.catagenda', verbose_name='Kategoria Ajenda'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='institute.institution', verbose_name='Instituisaun'),
        ),
        migrations.AlterField(
            model_name='catagenda',
            name='name_category',
            field=models.CharField(max_length=200, unique=True, verbose_name='Kategoria Ajenda'),
        ),
        migrations.AlterField(
            model_name='catagenda',
            name='name_category_slug',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Kategoria Ajenda Slug'),
        ),
        migrations.AlterField(
            model_name='commentinformative',
            name='problems',
            field=models.TextField(blank=True, verbose_name='Problema:'),
        ),
        migrations.AlterField(
            model_name='commentinformative',
            name='results',
            field=models.TextField(blank=True, verbose_name='Rezultadu:'),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='catagenda',
            field=models.CharField(max_length=25, null=True, verbose_name='Pendente'),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='institution',
            field=models.CharField(max_length=255, null=True, verbose_name='Kria Ajenda'),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ajenda'),
        ),
        migrations.AlterField(
            model_name='histagenda',
            name='title_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Titulu-Slug'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nota Informativu'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Titulu-Slug'),
        ),
        migrations.AlterField(
            model_name='requestagenda',
            name='catagenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestagenda', to='event.catagenda', verbose_name='Kategoria Ajenda:'),
        ),
        migrations.AlterField(
            model_name='requestagenda',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestagenda', to='institute.institution', verbose_name='Instituisaun:'),
        ),
        migrations.AlterField(
            model_name='requestagenda',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Pedidu Ajenda:'),
        ),
        migrations.AlterField(
            model_name='requestagenda',
            name='title_slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Titulu-Slug'),
        ),
        migrations.AlterField(
            model_name='yearagenda',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025, verbose_name='year'),
        ),
    ]
