# Generated by Django 4.2.19 on 2025-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0042_alter_agenda_options_alter_catagenda_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='end_time',
            field=models.DateTimeField(verbose_name='Instituisaun'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fatin'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='start_time',
            field=models.DateTimeField(verbose_name='Oras Hahu'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ajenda'),
        ),
    ]
