# Generated by Django 5.1.7 on 2025-03-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0043_alter_agenda_end_time_alter_agenda_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Tipu Enkontru'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='end_time',
            field=models.DateTimeField(verbose_name='Oras Remata'),
        ),
    ]
