# Generated by Django 5.1.7 on 2025-03-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0044_agenda_meeting_type_alter_agenda_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='histagenda',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Tipu Enkontru'),
        ),
    ]
