# Generated by Django 5.1.7 on 2025-03-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0045_histagenda_meeting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histagenda',
            name='meeting_type',
        ),
    ]
