# Generated by Django 5.1.7 on 2025-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0046_remove_histagenda_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipu Enkontru'),
        ),
    ]
