# Generated by Django 5.1.7 on 2025-03-22 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0047_alter_agenda_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='observation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='OBSERVASAUN'),
        ),
    ]
