# Generated by Django 5.1.7 on 2025-03-22 08:03

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0049_alter_agenda_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='observation',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='OBSERVASAUN'),
        ),
    ]
