# Generated by Django 5.1.7 on 2025-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0050_alter_agenda_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='histagenda',
            name='meeting_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tipu Enkontru'),
        ),
    ]
