# Generated by Django 5.1.7 on 2025-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0051_histagenda_meeting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=200, unique=True, verbose_name='Tipu Ajenda')),
                ('name_type_slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='Tipu Ajenda Slug')),
            ],
            options={
                'verbose_name_plural': 'Tipu Ajenda',
            },
        ),
    ]
