# Generated by Django 5.1.7 on 2025-03-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0052_typeagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='event.typeagenda', verbose_name='Tipu Ajenda'),
        ),
    ]
