# Generated by Django 5.1.7 on 2025-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0053_alter_agenda_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='agenda_files/', verbose_name='Dokumentu'),
        ),
    ]
