# Generated by Django 5.1.7 on 2026-03-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0054_agenda_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearagenda',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2026, verbose_name='year'),
        ),
    ]
