# Generated by Django 5.1.7 on 2026-08-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0055_alter_yearagenda_year"),
    ]

    operations = [
        migrations.RemoveField(model_name="agenda", name="user",),
    ]
