# Generated by Django 5.1.7 on 2026-08-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0056_remove_agenda_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="commentinformative", name="user",),
        migrations.RemoveField(model_name="histagenda", name="user",),
        migrations.RemoveField(model_name="informative", name="user",),
        migrations.RemoveField(model_name="requestagenda", name="user",),
    ]
