# Generated by Django 5.1.7 on 2026-08-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0057_remove_commentinformative_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="histagenda",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Ajenda"),
        ),
    ]
