# Generated by Django 5.1.7 on 2026-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0058_alter_histagenda_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="histagenda",
            name="title_slug",
            field=models.SlugField(max_length=255, verbose_name="Titulu-Slug"),
        ),
    ]
