# Generated by Django 5.1.7 on 2026-08-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0059_alter_histagenda_title_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaWhatsAppRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                (
                    "phone_number",
                    models.CharField(max_length=30, verbose_name="Numeru WhatsApp"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_recipients",
                        to="event.agenda",
                        verbose_name="Ajenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda WhatsApp Recipient",
                "verbose_name_plural": "Agenda WhatsApp Recipients",
            },
        ),
        migrations.CreateModel(
            name="AgendaNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("3_days", "3 Days Before"),
                            ("2_days", "2 Days Before"),
                            ("1_day", "1 Day Before"),
                            ("1_hour", "1 Hour Before"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("whatsapp_message_id", models.CharField(blank=True, max_length=255)),
                ("response", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_notifications",
                        to="event.agenda",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="event.agendawhatsapprecipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agenda Notification",
                "verbose_name_plural": "Agenda Notifications",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agenda", "recipient", "reminder_type"),
                        name="unique_agenda_whatsapp_recipient_reminder",
                    )
                ],
            },
        ),
    ]
