# Generated by Django 5.1.7 on 2026-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0060_agendawhatsapprecipient_agendanotification"),
    ]

    operations = [
        migrations.AlterModelOptions(name="agendawhatsapprecipient", options={},),
        migrations.AddField(
            model_name="agendawhatsapprecipient",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="agendawhatsapprecipient",
            name="send_email",
            field=models.BooleanField(default=True, verbose_name="Haruka Email"),
        ),
        migrations.AddField(
            model_name="agendawhatsapprecipient",
            name="send_whatsapp",
            field=models.BooleanField(default=False, verbose_name="Haruka WhatsApp"),
        ),
        migrations.AlterField(
            model_name="agendawhatsapprecipient",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativu"),
        ),
        migrations.AlterField(
            model_name="agendawhatsapprecipient",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Numeru WhatsApp"
            ),
        ),
    ]
