# Generated by Django 5.1.7 on 2026-08-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0061_alter_agendawhatsapprecipient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="agendawhatsapprecipient", name="agenda",),
        migrations.DeleteModel(name="AgendaNotification",),
        migrations.DeleteModel(name="AgendaWhatsAppRecipient",),
    ]
