# Generated by Django 5.1.7 on 2026-08-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0062_remove_agendawhatsapprecipient_agenda_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Naran")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="event.agenda",
                        verbose_name="Ajenda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgendaNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("1_day", "1 Day Before"),
                            ("2_hours", "2 Hours Before"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_notifications",
                        to="event.agenda",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="event.agendarecipient",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agenda", "recipient", "reminder_type"),
                        name="unique_agenda_email_reminder",
                    )
                ],
            },
        ),
    ]
