# Generated by Django 5.1.7 on 2026-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0063_agendarecipient_agendanotification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendarecipient",
            options={
                "ordering": ["name"],
                "verbose_name": "Agenda Recipient",
                "verbose_name_plural": "Agenda Recipients",
            },
        ),
        migrations.RemoveField(model_name="agendarecipient", name="agenda",),
        migrations.AddField(
            model_name="agenda",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                related_name="agendas",
                to="event.agendarecipient",
                verbose_name="Receptor Email",
            ),
        ),
        migrations.AddField(
            model_name="agendarecipient",
            name="is_default",
            field=models.BooleanField(
                default=False, verbose_name="Simu Ajenda Automaticamente"
            ),
        ),
        migrations.AddField(
            model_name="agendarecipient",
            name="position",
            field=models.CharField(blank=True, max_length=150, verbose_name="Kargu"),
        ),
        migrations.AlterField(
            model_name="agendarecipient",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
