# Generated by Django 5.1.7 on 2026-08-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0064_alter_agendarecipient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendanotification",
            name="reminder_type",
            field=models.CharField(
                choices=[("1_day", "1 Day Before"), ("1_hour", "1 Hour Before")],
                max_length=20,
            ),
        ),
    ]
