# Generated by Django 5.1.7 on 2026-08-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0065_alter_agendanotification_reminder_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendanotification",
            name="reminder_type",
            field=models.CharField(
                choices=[("1_day", "1 Day Before"), ("2_hours", "2 Hours Before")],
                max_length=20,
            ),
        ),
    ]
