# Generated by Django 5.1.7 on 2026-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0066_alter_agendanotification_reminder_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="agendarecipient",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
