# Generated by Django 5.1.7 on 2026-08-13 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0067_agenda_uuid_agendarecipient_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="agendarecipient",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
