# Generated by Django 5.1.7 on 2026-08-21 00:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0068_alter_agenda_uuid_alter_agendarecipient_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaTo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100, verbose_name="Naran")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgendaDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delegated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data no Oras Delegasaun",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nota Delegasaun"
                    ),
                ),
                (
                    "central_user_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "central_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="event.agenda",
                        verbose_name="Ajenda",
                    ),
                ),
                (
                    "delegated_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_from",
                        to="event.agendato",
                        verbose_name="Delega Husi",
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_to",
                        to="event.agendato",
                        verbose_name="Delega Ba",
                    ),
                ),
            ],
            options={"ordering": ("-delegated_at",),},
        ),
    ]
