# Generated by Django 5.1.7 on 2026-08-21 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0069_agendato_agendadelegation"),
    ]

    operations = [
        migrations.RemoveField(model_name="agendato", name="code",),
        migrations.AddField(
            model_name="agendato",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="agendato",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Naran"),
        ),
    ]
