# Generated by Django 5.1.7 on 2026-08-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0071_typeagenda_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typeagenda",
            options={
                "ordering": ["name_type"],
                "verbose_name": "Tipu Ajenda",
                "verbose_name_plural": "Tipu Ajenda",
            },
        ),
        migrations.AlterField(
            model_name="typeagenda",
            name="name_type_slug",
            field=models.SlugField(
                blank=True,
                default=1,
                max_length=255,
                unique=True,
                verbose_name="Tipu Ajenda Slug",
            ),
            preserve_default=False,
        ),
    ]
