# Generated by Django 5.1.7 on 2026-08-21 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0072_alter_typeagenda_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagenda",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
