# Generated by Django 5.1.7 on 2026-08-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0073_catagenda_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catagenda",
            options={
                "ordering": ["name_category"],
                "verbose_name": "Kategoria Ajenda",
                "verbose_name_plural": "Kategoria Ajenda",
            },
        ),
        migrations.AddField(
            model_name="agendato",
            name="code",
            field=models.CharField(
                default=1, max_length=50, unique=True, verbose_name="Kodigu"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="catagenda",
            name="name_category_slug",
            field=models.SlugField(
                blank=True,
                default=1,
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="Kategoria Ajenda Slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="typeagenda",
            name="name_type_slug",
            field=models.SlugField(
                blank=True,
                editable=False,
                max_length=255,
                unique=True,
                verbose_name="Tipu Ajenda Slug",
            ),
        ),
    ]
