# Generated by Django 5.1.7 on 2026-08-22 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0074_alter_catagenda_options_agendato_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendadelegation",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
