# Generated by Django 5.1.7 on 2026-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0075_agendadelegation_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenda",
            name="central_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="Central User ID",
            ),
        ),
        migrations.AddField(
            model_name="agenda",
            name="central_username",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=150,
                null=True,
                verbose_name="Central Username",
            ),
        ),
    ]
