# Generated by Django 5.1.7 on 2026-08-22 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0076_agenda_central_user_id_agenda_central_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[
                            ("ajenda_user", "Ministro"),
                            ("ajenda_vmn", "Vice Ministro"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("AGENDA_NEW", "Ajenda Foun"),
                            ("AGENDA_UPDATE", "Ajenda Atualizadu"),
                            ("DELEGATION", "Delegasaun"),
                            ("REMINDER", "Reminder"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "created_by_user_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "created_by_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "agenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="event.agenda",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("central_user_id", models.CharField(db_index=True, max_length=100)),
                (
                    "central_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="event.notification",
                    ),
                ),
            ],
            options={"unique_together": {("notification", "central_user_id")},},
        ),
    ]
