# Generated by Django 5.1.7 on 2026-08-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0077_notification_notificationread"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notifikasaun",
                "verbose_name_plural": "Notifikasaun",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationread",
            options={
                "verbose_name": "Notifikasaun Le'e",
                "verbose_name_plural": "Notifikasaun Le'e",
            },
        ),
        migrations.AlterUniqueTogether(name="notificationread", unique_together=set(),),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="Mensajen"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("AGENDA_NEW", "Ajenda Foun"),
                    ("AGENDA_UPDATE", "Ajenda Atualizadu"),
                    ("DELEGATION", "Delegasaun"),
                    ("REMINDER", "Reminder"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Tipu Notifikasaun",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipient_role",
            field=models.CharField(
                choices=[("ajenda_user", "Ministro"), ("ajenda_vmn", "Vice Ministro")],
                db_index=True,
                max_length=50,
                verbose_name="Recipient Role",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titulu"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient_role", "notification_type", "created_at"],
                name="event_notif_recipie_04bc66_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationread",
            constraint=models.UniqueConstraint(
                fields=("notification", "central_user_id"),
                name="unique_notification_read_user",
            ),
        ),
    ]
