# Generated by Django 4.1.5 on 2023-02-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_media',
            field=models.BooleanField(default=False, verbose_name='MEDIA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='SECRETARY'),
        ),
    ]
