# Generated by Django 4.2.19 on 2025-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_is_media_alter_user_is_secretary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_adj',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_dei',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_media',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_secretary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_uap',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_ucvq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_uedc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_uga',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
