# Generated by Django 4.2.19 on 2025-03-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_is_adj_remove_user_is_dei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adj',
            field=models.BooleanField(default=False, verbose_name='Adjunto'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dei',
            field=models.BooleanField(default=False, verbose_name='Director'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_media',
            field=models.BooleanField(default=False, verbose_name='MEDIA'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='SECRETARY'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_uap',
            field=models.BooleanField(default=False, verbose_name='UAP'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ucvq',
            field=models.BooleanField(default=False, verbose_name='UCVQ'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_uedc',
            field=models.BooleanField(default=False, verbose_name='UEDC'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_uga',
            field=models.BooleanField(default=False, verbose_name='UGA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
