# Generated by Django 4.1.5 on 2023-04-12 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name_plural': 'Logo'},
        ),
    ]
