# Generated by Django 4.1.5 on 2023-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institution', models.CharField(max_length=255, null=True, verbose_name='Institute Invited')),
            ],
            options={
                'verbose_name_plural': 'Institute Invited',
            },
        ),
    ]
