# Generated by Django 4.1.5 on 2023-02-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_name_institution_invitedinstitute_name_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_invitedas', models.CharField(max_length=255, null=True, verbose_name='Invited AS')),
            ],
            options={
                'verbose_name_plural': 'Institute Invited',
            },
        ),
    ]
