# Generated by Django 4.1.5 on 2023-02-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_invitedas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitedAs',
            new_name='Attencence',
        ),
        migrations.RenameField(
            model_name='attencence',
            old_name='name_invitedas',
            new_name='name_attendence',
        ),
    ]
