# Generated by Django 4.1.5 on 2023-02-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_rename_attencence_attendence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'verbose_name_plural': 'Category Attendence'},
        ),
        migrations.AlterField(
            model_name='attendence',
            name='name_attendence',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Attendence'),
        ),
    ]
