# Generated by Django 4.1.5 on 2023-02-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_agenda_invitedinstitue_and_more'),
        ('institute', '0007_alter_attendence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institution', models.CharField(max_length=255, null=True, verbose_name='Institution Invited')),
            ],
            options={
                'verbose_name_plural': 'Institution Invited',
            },
        ),
        migrations.DeleteModel(
            name='InvitedInstitute',
        ),
    ]
