# Generated by Django 4.2.19 on 2025-02-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_alter_departmentadn_options_alter_unitadn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendence',
            options={'verbose_name_plural': 'Atendente'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name_plural': 'Instituisaun Nebe Konvida'},
        ),
        migrations.AlterField(
            model_name='attendence',
            name='name_attendence',
            field=models.CharField(max_length=255, null=True, verbose_name='Atendente'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name_institution',
            field=models.CharField(max_length=255, null=True, verbose_name='Naran Instituisaun:'),
        ),
    ]
