# Generated by Django 5.1.7 on 2026-08-13 07:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "institute",
            "0013_alter_attendence_options_alter_institution_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
