# Generated by Django 5.1.7 on 2026-08-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0014_institution_uuid"),
    ]

    operations = [
        migrations.RemoveField(model_name="institution", name="uuid",),
    ]
