# Generated by Django 5.1.7 on 2026-08-13 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institute", "0015_remove_institution_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
