# Generated by Django 4.1.5 on 2023-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='Name-Slug')),
            ],
            options={
                'verbose_name_plural': 'Semetral',
            },
        ),
        migrations.CreateModel(
            name='Trimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('name_slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='Name-Slug')),
            ],
            options={
                'verbose_name_plural': 'Trimestral',
            },
        ),
    ]
