# Generated by Django 4.1.5 on 2023-03-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_mensual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensual',
            options={'verbose_name_plural': 'Mensual'},
        ),
    ]
