# Generated by Django 4.1.5 on 2023-03-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_mensual_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default=None, upload_to='logo', verbose_name='Logo ADN')),
            ],
        ),
    ]
